### ISSUE TITLE
Login with OpenID

### ISSUE THREAD

**Issue by Yolgie** [Yolgie/jku-lan-se#21]
A user wants to use his existing OpenID User to login

**Comment by Yolgie** [comment]
https://openid.net/developers/specs/
http://www.ibm.com/developerworks/library/j-openid/
https://stackoverflow.com/questions/1420791/getting-started-with-openid

**Comment by Yolgie** [comment]
Steam as an OpenID Provider: https://steamcommunity.com/dev (from #22 )

**Comment by fuero** [comment]
done
