### ISSUE TITLE
Fix package structure

### ISSUE THREAD

**Issue by Yolgie** [Yolgie/jku-lan-se#37]
Fix package structure to: at.jku.oeh.jku-lan.

**Comment by Yolgie** [comment]
Help wanted for name of the Project!

**Comment by TTH-Someone-stole-my-name** [comment]
Wie wärs mit "manager"  ? Also at.jku.oeh.jku-lan.manager

**Comment by Yolgie** [comment]
jo, hab ich auch schon gedacht

**Comment by SecMeyo** [comment]
des klingt aber so normal :/ lanager wär hald cool, gibts aber schon
